### ISSUE TITLE
Get extension in google store in a manner that deters or prevents downloads except from those invited.

### ISSUE THREAD

**Issue by jakedurell** [codeforbtv/expunge-vt#110]

**Comment by ereynolds123** [comment]
(1) https://support.google.com/chrome/a/answer/2714278?hl=en

(2) https://developer.chrome.com/webstore/publish

There are two ways to go about limiting who can download the app. 
    1. Make the app "Private". "Only users in your domain can see and install the app or extension. Or, you can restrict the app or extension to trusted testers that you specified in your developer dashboard."- (1) This has the pro of restricting who has access to the app.
    2. Make the app "Unlisted". "Only users with the app or extension link can see and install it. The app doesn’t appear in the Chrome Web Store search results. You can share the app or extension link with users outside your domain." This has the pro that the extension could be given to attorneys. The con is that it still functions as a back end work around. 

I would recommend making the app "Private" because this would allow attorneys in our domain to see the app in the Google Chrome store and no one not in our domain would see the extension. You could also give the extension link to attorneys outside the domain.
